Use publish plugin to build MPK
mendix/AuditTrailModule pull request #42
Opened 2023-02-09 16:02 UTC by dahfjkg

2023-02-10 13:03 UTC, hugomendix requested changes

2023-02-10 13:03 UTC, hugomendix commented on marketplace/description.html
> +This module ensures tracking of the changes made in the system. We support 2 major versions of this module: - Version 9 is compatible with Atlas UI 3. It is only available in Mendix 9. It should be u
Maybe you could use HTML tags to layout the bullet items more nicely.

2023-02-10 15:56 UTC, dahfjkg commented
rebased on `dat/timezone-logging` ⬆️

2023-02-10 15:58 UTC, dahfjkg commented on build.gradle
> +mxBuild.dependsOn prepareTest
`exportModule` comes from the plugin, so `exportModule.dependsOn prepareMpk` should be enough. I will add the rest.

2023-02-15 16:25 UTC, hugomendix commented
LGTM

2023-02-15 16:25 UTC, hugomendix submitted a review, later dismissed

2023-02-16 07:45 UTC, hugomendix approved these changes

2023-02-16 09:33 UTC, hugomendix approved these changes

2023-02-16 09:42 UTC, merged